# Generated by Django 4.1.1 on 2022-12-09 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eyes', '0002_alter_information_leftimg_alter_information_rightimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='leftimg',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='information',
            name='rightimg',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
