# Generated by Django 4.1.1 on 2022-12-12 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eyes', '0003_alter_information_leftimg_alter_information_rightimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='leftdr',
            field=models.CharField(default='default', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='information',
            name='rightdr',
            field=models.CharField(default='default', max_length=50),
            preserve_default=False,
        ),
    ]
